// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJYR0X5aORrggOS6qNsySWDAAKnF8h58',
    appId: '1:1004561010857:web:4ed97b60b686d6b6ccd9b8',
    messagingSenderId: '1004561010857',
    projectId: 'seimeisocialapp',
    authDomain: 'seimeisocialapp.firebaseapp.com',
    storageBucket: 'seimeisocialapp.firebasestorage.app',
    measurementId: 'G-ZSVLDDWSQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRDew6if3tk7bgIjwhZDOs7HE67gOzf60',
    appId: '1:1004561010857:android:eb71b27b056bd6d7ccd9b8',
    messagingSenderId: '1004561010857',
    projectId: 'seimeisocialapp',
    storageBucket: 'seimeisocialapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALgT0j3NVbhFnSmIKb-lgACD1KJg9XG8A',
    appId: '1:1004561010857:ios:d14df153327fa1c5ccd9b8',
    messagingSenderId: '1004561010857',
    projectId: 'seimeisocialapp',
    storageBucket: 'seimeisocialapp.firebasestorage.app',
    iosBundleId: 'com.example.seimeiSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALgT0j3NVbhFnSmIKb-lgACD1KJg9XG8A',
    appId: '1:1004561010857:ios:d14df153327fa1c5ccd9b8',
    messagingSenderId: '1004561010857',
    projectId: 'seimeisocialapp',
    storageBucket: 'seimeisocialapp.firebasestorage.app',
    iosBundleId: 'com.example.seimeiSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRJYR0X5aORrggOS6qNsySWDAAKnF8h58',
    appId: '1:1004561010857:web:c8707df31fbb6db0ccd9b8',
    messagingSenderId: '1004561010857',
    projectId: 'seimeisocialapp',
    authDomain: 'seimeisocialapp.firebaseapp.com',
    storageBucket: 'seimeisocialapp.firebasestorage.app',
    measurementId: 'G-GMB3K590GR',
  );
}
